Update release notes draft to version v1.21.0-alpha.2
kubernetes/sig-release pull request #1462
Opened 2021-02-11 18:41 UTC by soniasingla

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.21.0-alpha.2

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

2021-02-11 18:58 UTC, wilsonehusin requested changes
I have some concerns, but since you made more edits I don't want you to go through the whole process again right now.

can you please add comment on the files I pointed out with `# TODO`? we'll get back to it in the next PR

2021-02-11 18:58 UTC, wilsonehusin commented on releases/release-1.21/release-notes/maps/pr-97543-map.yaml
> +  text: remove LegacyNodeRoleBehavior and mv ServiceNodeExclusion to GA
I can see the intent but I'm worried that this doesn't represent the actual change.

2021-02-11 18:58 UTC, wilsonehusin commented on releases/release-1.21/release-notes/maps/pr-97193-map.yaml
> +  text: fix devicemanager TestDevicePluginReRegistrationProbeMode failed
```yaml
releasenote:
  text: fix flaky failure on devicemanager TestDevicePluginReRegistrationProbeMode
```
might fit better?

2021-02-11 18:58 UTC, wilsonehusin commented on releases/release-1.21/release-notes-draft.json
> +{
@puerco the JSON prettifier works!

2021-02-12 17:32 UTC, wilsonehusin commented
if #1463 gets merged before this one, then we can find out the delta later and add in the changes that was not covered by #1463.

2021-02-16 17:10 UTC, wilsonehusin commented on releases/release-1.21/release-notes/maps/pr-96691-map.yaml
> +  text: Increase timeout for pod lifecycle test to reach pod status=ready
I think this needs `do_not_publish: false` because it's not showing up in the markdown above

2021-02-17 16:36 UTC, wilsonehusin commented
/lgtm
/assign @palnabarun

2021-02-17 17:57 UTC, palnabarun commented
/milestone v1.21

2021-02-17 17:57 UTC, palnabarun commented
/approve

Thank you @soniasingla @wilsonehusin 🎉

2021-02-17 17:59 UTC, merged

2021-02-17 20:52 UTC, wilsonehusin commented on releases/release-1.21/release-notes/maps/pr-97543-map.yaml
> +  text: remove LegacyNodeRoleBehavior and mv ServiceNodeExclusion to GA
to elaborate -- the wording "unconditionally enabled" is important for feature gates, roughly:

- alpha: default to false, can be enabled if consumers choose to
- beta: default to true, can be disabled if consumers choose to
- generally available (GA): always true, cannot be turned off