Update release cut issue template
kubernetes/sig-release pull request #1524
Opened 2021-04-16 02:54 UTC by puerco

#### What type of PR is this:

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

This PR modifies the release cut issue template to add links to docs and quick hints for the release manager.
It updates all sections to current practices, dropping redundant information.

Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

2021-04-16 04:01 UTC, justaugustus requested changes
I was just thinking of some template updates!
@puerco -- can you add a session at the top for "Release Blocking Issues"?

2021-04-16 07:38 UTC, saschagrunert commented on .github/ISSUE_TEMPLATE/cut-release.md
> +## Scheduled to happen: <!-- Tue, 2021-02-26 -->
```suggestion
## Scheduled to happen: <!-- Tue, 2021-MM-DD -->
```

2021-04-17 18:40 UTC, puerco commented
Nit fixed and I added the "Release Blocking Issues" section at the top.

2021-04-17 18:40 UTC, puerco commented on .github/ISSUE_TEMPLATE/cut-release.md
> +## Scheduled to happen: <!-- Tue, 2021-02-26 -->
:+1:

2021-04-28 09:37 UTC, saschagrunert approved these changes

2021-04-28 09:38 UTC, merged