Update 1.22 comms team
kubernetes/sig-release pull request #1591
Opened 2021-06-10 23:44 UTC by savitharaghunathan

#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Updating 1.22 comms team. Moving Jesse Butler to comms lead and adding an additional row to honor Peeyush

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

/assign @annajung @divya-mohan0209 @erismaster @kikisdeliveryservice 
/cc @jeremyrickard @hasheddan @justaugustus @saschagrunert

2021-06-10 23:45 UTC, savitharaghunathan commented
/approve cancel
/priority critical-urgent

2021-06-10 23:46 UTC, puerco commented on releases/release-1.22/release-team.md
> +| Lead in Memoriam | Peeyush Gupta ([@pensu](https://github.com/pensu) / Slack: `@pensu91`) | |
:heart:

2021-06-10 23:46 UTC, puerco commented
/lgtm

2021-06-10 23:49 UTC, savitharaghunathan commented
> Thank you Savitha 🤗
Thank you @puerco <3 I procrastinated a bit on updating this doc and it's time now. This is the toughest one-liner PR I have ever made.

2021-06-10 23:51 UTC, savitharaghunathan commented
/cc @puerco @cpanato 
Sorry, I wasn't thinking while adding the cc list. My apologies

2021-06-10 23:57 UTC, puerco commented
We still have to finish our onboarding, but I can try :)
/approve

2021-06-10 23:59 UTC, justaugustus requested changes
@savitharaghunathan -- Thank you for memorializing Peeyush here!

Can we go a step further and add a link to his [CNCF memorial page](https://github.com/cncf/memorials/blob/main/peeyush-gupta.md), which includes a link to donate to the family?

2021-06-11 00:03 UTC, savitharaghunathan commented
> @savitharaghunathan -- Thank you for memorializing Peeyush here!
> 
> Can we go a step further and add a link to his [CNCF memorial page](https://github.com/cncf/memorials/blob/main/peeyush-gupta.md), which includes a link to donate to the family?

Yes of course. Thank you @justaugustus. @mrbobbytables mentioned that as well. Update coming right away

2021-06-11 00:08 UTC, savitharaghunathan commented
@justaugustus done. PTAL :) Let me know if should add it as a column instead of hyperlinking to the name

2021-06-11 00:48 UTC, justaugustus commented
> @justaugustus done. PTAL :) Let me know if should add it as a column instead of hyperlinking to the name

Hmmmm, how about this:
- Pull this out of the table, under the Release Manager note in a separate `## In Memoriam` heading
- List the CNCF memorial page
- List the donation page

2021-06-11 01:02 UTC, savitharaghunathan commented
@justaugustus Thanks for the super reviews. I moved it to a separate section at the end. Should I mention anything else?

2021-06-11 07:18 UTC, saschagrunert approved these changes
:heart: 
/lgtm
/hold
feel free to unhold if everything is fine

2021-06-11 07:33 UTC, cpanato commented
/lgtm
<3

2021-06-11 14:09 UTC, justaugustus commented on releases/release-1.22/release-team.md
> +- [Peeyush Gupta: Family Education Fund](https://milaap.org/fundraisers/support-peeyush-gupta-family-education)
```suggestion
- [Peeyush Gupta](https://github.com/cncf/memorials/blob/main/peeyush-gupta.md) (Emeritus Communications Lead)
  
  [Peeyush Gupta: Family Education Fund](https://milaap.org/fundraisers/support-peeyush-gupta-family-education)
```

2021-06-11 14:11 UTC, justaugustus approved these changes
@savitharaghunathan -- Committed a tiny tweak to formatting and called out the Communications role as well.

Thank you again for adding this!
/lgtm
/approve

2021-06-11 14:13 UTC, justaugustus commented
/hold cancel

2021-06-11 14:15 UTC, merged