Release-1.23: update links on release-1.23 README.md
kubernetes/sig-release pull request #1664
Opened 2021-08-16 16:20 UTC by reylejano

#### What type of PR is this:
/kind cleanup

#### What this PR does / why we need it:
This PR updates the following links on the release-1.23 README.md:
- Meeting minutes
- Internal contact info
- Retro document
- kubernetes/sig-release v1.23 milestone

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
None

/sig release
/area release-team
/priority critical-urgent
/assign @justaugustus @saschagrunert @jeremyrickard @cpanato @puerco @hasheddan
/cc @JamesLaverack @jrsapi @mkorbi @MonzElmasry

2021-08-16 18:42 UTC, justaugustus requested changes
@reylejano -- A few nits! :)

2021-08-16 18:42 UTC, justaugustus commented on releases/release-1.23/README.md
> +* [Internal Contact Info][http://bit.ly/k8s123-contacts] (accessible only to members of [kubernetes-release-team@])
Let's update this in the links section at the bottom of the document instead. (Line 93)

2021-08-16 18:42 UTC, justaugustus commented on releases/release-1.23/README.md
> +* [Retrospective Document][http://bit.ly/k8s123-retro]
Let's update this in the links section at the bottom of the document instead. (Line 94)

2021-08-16 18:42 UTC, justaugustus commented on releases/release-1.23/README.md
> +* [Internal Contact Info][http://bit.ly/k8s123-contacts] (accessible only to members of [kubernetes-release-team@])
also: s/`[kubernetes-release-team@]`/`[release-team@]` here and on line 103

2021-08-17 00:17 UTC, justaugustus requested changes
@reylejano -- I have more ~presents~ nits for you :P

2021-08-17 00:17 UTC, justaugustus commented on releases/release-1.23/README.md
> +[Internal Contact Info]: http://bit.ly/k8s123-contacts
```suggestion
[Internal Contact Info]: https://bit.ly/k8s123-contacts
```

2021-08-17 00:17 UTC, justaugustus commented on releases/release-1.23/README.md
> +[Retrospective Document]: http://bit.ly/k8s123-retro
```suggestion
[Retrospective Document]: https://bit.ly/k8s123-retro
```

2021-08-17 00:17 UTC, justaugustus commented on releases/release-1.23/README.md
>  [kubernetes-release-team@]: https://groups.google.com/a/kubernetes.io/g/release-team
```suggestion
[release-team@]: https://groups.google.com/a/kubernetes.io/g/release-team
```

2021-08-17 00:17 UTC, justaugustus commented on releases/release-1.23/README.md
> +[release-team@]: https://github.com/kubernetes/sig-release/blob/master/releases/release-1.23/release-team.md
```suggestion
```

2021-08-17 00:17 UTC, justaugustus commented on releases/release-1.23/README.md
> +* [Internal Contact Info][Internal Contact Info] (accessible only to members of [kubernetes-release-team@]/[release-team@])
```suggestion
* [Internal Contact Info] (accessible only to members of [release-team@])
```

1. As the link is identical, there's no need to reference it twice
2. We drop the reference to `kubernetes-release-team@` as it's a deprecated list

2021-08-17 05:40 UTC, reylejano commented
@justaugustus , committed suggestions. Thank you!

2021-08-17 07:37 UTC, saschagrunert approved these changes

2021-08-17 07:40 UTC, merged