Document timeliness of exception request as assessment criteria
kubernetes/sig-release pull request #1673
Opened 2021-08-19 18:17 UTC by JamesLaverack

#### What type of PR is this:

/kind cleanup

#### What this PR does / why we need it:

Following on from the discussion in the Kubernetes 1.22 release retrospective — this clarifies that release team may consider the timeliness of an exception request as part of the assessment criteria when deciding if to grant an exception.

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

2021-08-19 18:18 UTC, JamesLaverack commented
/kind documentation

2021-08-24 07:18 UTC, justaugustus requested changes
@JamesLaverack -- Thanks for filing this! Just a couple of nits on language.

2021-08-24 07:18 UTC, justaugustus commented on releases/EXCEPTIONS.md
> +Exceptions should be filed at the earliest oppitunity, including before the deadline if it is likely to miss.
```suggestion
Exceptions should be filed at the earliest opportunity i.e., as soon as it's clear an enhancement may miss the deadline
```

2021-08-29 23:52 UTC, JamesLaverack commented
@justaugustus Thanks for the review, I've updated the language as per your suggestion. :)

2021-09-01 22:20 UTC, justaugustus approved these changes
Thanks again for the update, @JamesLaverack!
/label tide/merge-method-squash

2021-09-01 22:21 UTC, merged