Release Lead handbook updates and clarifications
kubernetes/sig-release pull request #1812
Opened 2022-01-12 15:51 UTC by JamesLaverack

#### What type of PR is this:

/kind documentation

#### What this PR does / why we need it:

Release Lead handbook updates and clarifications.

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

2022-01-12 15:51 UTC, JamesLaverack commented
/priority important-longterm

2022-06-06 09:14 UTC, palnabarun commented
@JamesLaverack -- are you planning to continue on this?

/remove-lifecycle rotten

2022-06-06 09:37 UTC, JamesLaverack commented
> @JamesLaverack -- are you planning to continue on this?
> 
> 
> 
> /remove-lifecycle rotten

Yes! :D

2022-09-29 09:32 UTC, leonardpahlke requested changes

2022-09-29 09:32 UTC, leonardpahlke commented on release-team/role-handbooks/release-team-lead/README.md
```suggestion
- Kubernetes 1.24: Stargazer
- Kubernetes 1.25: Combiner

```

2022-09-29 09:32 UTC, leonardpahlke commented on release-team/role-handbooks/release-team-lead/README.md
> +  - Burndown/Meeting Minutes: `https://bit.ly/k8sXYY-burndown`
Why Is this link needed? (I cannot find it being used for previous releases)

2022-09-29 09:32 UTC, leonardpahlke commented on release-team/role-handbooks/release-team-lead/README.md
> +- Short links are handled with [https://bit.ly](https://bit.ly). Each release should have the following documents (replacing XYY with the release version number minus dots):
```suggestion
Short links are handled with [https://bit.ly](https://bit.ly). Currently there is no shared account, so the Release Lead must use their own free-tier account. Each release should have the following documents (replacing **XYY** with the release version number minus dots):
```

2022-09-29 09:32 UTC, leonardpahlke commented on release-team/role-handbooks/release-team-lead/README.md
> +    in-development release, and all SIG Release chairs and technical leads.
not sure if this is needed; this might just lengthen this document and is very obvious when opening the OWNER_ALIASES file; WDYT

2023-03-05 06:35 UTC, closed without merging