add CI Signal onboarding handbook
kubernetes/sig-release pull request #1869
Opened 2022-03-26 11:49 UTC by leonardpahlke

#### What type of PR is this:
/kind documentation

#### What this PR does / why we need it:

Currently, it is difficult to get a clear picture of what CI Signal is doing without reading 20 pages of the CI Signal manual. By adding a "one-pager" manual that provides an overview of responsibilities, the onboarding experience and team responsibilities can be more clearly communicated (see issue https://github.com/kubernetes/sig-release/issues/1857). This topic has been discussed in a sig-release meeting on 2022-03-22 see [agenda](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit)

#### Which issue(s) this PR fixes:

Fixes: https://github.com/kubernetes/sig-release/issues/1857

#### Special notes for your reviewer:

We are currently working on some additional videos which will be added later (see issue https://github.com/kubernetes/sig-release/issues/1856).

cc @kubernetes/ci-signal

2022-03-26 11:52 UTC, leonardpahlke commented
cc @RobertKielty

2022-04-02 14:17 UTC, mkorbi commented
Why not just add/update https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/ci-signal#overview-of-ci-signal-responsibilities ? Because I don't read it as an onboarding document, it is an overview of tasks. Also, it would need to be made clear the difference between this section of [onboarding](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/ci-signal#onboarding).

Sprawling information, making it redundant, and maybe being formalized in different explanations is more counterproductive.

2022-04-05 11:21 UTC, leonardpahlke commented
The idea was to have a one pager that we can share to ones interested in the team and to everybody who is interested applying for ci signal shadow.
It can also be used as onboarding sheet but I agree there is aleady a section in the current handbook. So maybe rename it? 

release-team/role-handbooks/ci-signal/onboarding.md -> release-team/role-handbooks/ci-signal/one-pager.md

and write **ONE PAGER** ro something in the header

cc @kubernetes/ci-signal

2022-04-25 08:25 UTC, mkorbi requested changes

2022-04-25 08:25 UTC, mkorbi commented on release-team/role-handbooks/ci-signal/one-pager.md
> +1. Monitor Testgrid: The team is particularly interested the [testgrid dashboards](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/ci-signal/README.md#blocking-vs-in
The team is particularly interested in the [testgrid dashboards]

2022-04-25 08:25 UTC, mkorbi commented on release-team/role-handbooks/ci-signal/one-pager.md
> +3. Track GitHub issues: Follow up on github issues, talk to [other sigs](https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/ci-signal/README.md#working-with-sigs-outsid
needs a space between
"ping and cc people. You may add"

2022-04-25 11:37 UTC, mkorbi approved these changes
lgtm

2022-04-25 11:39 UTC, merged