Update release notes draft to version v1.26.0-alpha.1
kubernetes/sig-release pull request #2059
Opened 2022-10-19 21:37 UTC by sayantani11

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.26.0-alpha.1

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

2022-10-19 21:38 UTC, sayantani11 commented
/assign @ramrodo

2022-10-19 21:41 UTC, sayantani11 commented
So basically what happened here is, after that error popped up I ran the command again, and it asked me if I'd like to continue from where i left. I did that, and after a few prs the error popped up again. I did the same but this time I exited and did `Ctrl +C` and it gave an option if I would like to make a pr of the release note edited still now. I did and it created this pr. Although it worked but I don't think it's the correct of doing the task tho🤔

2022-10-20 15:49 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-108832-map.yaml
> +  text: fixed relative cpu priority for pods where containers explicitly request zero
```suggestion
  text: Fixed relative cpu priority for pods where containers explicitly request zero
```

2022-10-20 15:50 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-108832-map.yaml
> +    avoid possible cpu starvation of other pods
```suggestion
    avoid possible cpu starvation of other pods.
```

2022-10-20 15:50 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-111420-map.yaml
> +  text: '"NONE"'
Remove this whole entry since the release note is `NONE`

```suggestion
```

2022-10-20 15:51 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-111708-map.yaml
> +  text: release-note
Remove this empty release note

```suggestion
```

2022-10-20 16:22 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-111783-map.yaml
> +  text: 'kubeadm: tries to load CA cert from external CertificateAuthority file when
```suggestion
pr: 111783
releasenote:
  text: 'kubeadm: tried to load CA cert from external CertificateAuthority file when
```

2022-10-20 16:23 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-111783-map.yaml
> +    CertificateAuthorityData is empty for existing kubeconfig'
```suggestion
    CertificateAuthorityData is empty for existing kubeconfig.'
```

2022-10-20 16:24 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-112157-map.yaml
> +  text: Avoided propagating hosts' `search .` into containers' `/etc/resolv.conf`
```suggestion
  text: Avoided propagating hosts `search .` into containers in `/etc/resolv.conf`
```

2022-10-20 16:25 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-112386-map.yaml
> +  text: CSRDuration feature gate that graduated to GA in 1.24 and was unconditionally
```suggestion
  text: `CSRDuration` feature gate that graduated to GA in 1.24 and was unconditionally
```

2022-10-20 16:26 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-112386-map.yaml
> +    enabled removed in v1.26
```suggestion
    enabled removed now in v1.26
```

2022-10-20 16:27 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-112427-map.yaml
> +  text: Allowed Label section in vsphere e2e cloudprovider configuration
```suggestion
  text: Allowed `Labels` section in vSphere e2e cloud provider configuration.
```

2022-10-20 16:28 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-67782-map.yaml
> +    has been removed. Please use the external cloud provider and csi driver from https://github.com/kubernetes/cloud-provider-openstack
```suggestion
    has been removed. Please use the external cloud provider and csi driver from [cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack)
```

2022-10-20 16:29 UTC, ramrodo requested changes
Great work!
Just a few comments

2022-10-24 15:35 UTC, ramrodo commented
Thanks, @sayantani11!
/lgtm
/approve

2022-10-24 15:36 UTC, merged