Update release notes draft to version v1.26.0-alpha.3
kubernetes/sig-release pull request #2085
Opened 2022-11-12 23:13 UTC by AnaMMedina21

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.26.0-alpha.3

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

2022-11-12 23:26 UTC, AnaMMedina21 commented
It's ready for review :) @ramrodo @harshanarayana @sayantani11 @laxmikantbpandhare

2022-11-14 06:22 UTC, laxmikantbpandhare commented
/assign @ramrodo

2022-11-14 17:17 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-108501-map.yaml
> +  text: Enabled `kube-controller-manager` to support '--concurrent-horizontal-pod-autoscaler-syncs'
Please use backticks when a flag or command is found:

```suggestion
  text: Enabled `kube-controller-manager` to support `--concurrent-horizontal-pod-autoscaler-syncs`
```

2022-11-14 17:19 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-110559-map.yaml
> +    annotation), choose the newest one instead of throwing an error.'
I think there is an extra single quote:

```suggestion
    annotation), choose the newest one instead of throwing an error.
```

2022-11-14 17:22 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-111973-map.yaml
> +    See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26 for
Use `[]()` markdown syntax for links:

```suggestion
    See [deprecation guide for 1.26](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26) for
```

2022-11-14 17:22 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-112058-map.yaml
> +  text: Updated `cri-tools` to [v1.25.0(https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.25.0)
Missing closing bracket:

```suggestion
  text: Updated `cri-tools` to [v1.25.0](https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.25.0)
```

2022-11-14 17:27 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-113113-map.yaml
> +    longer, it \nnow includes the time duration of the unreserve operation."
```suggestion
    longer, it now includes the time duration of the unreserve operation."
```

2022-11-14 17:28 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-113198-map.yaml
> +  text: <NONE>
Remove this entire file since there is no release note for that PR

2022-11-14 17:31 UTC, ramrodo commented on releases/release-1.26/release-notes/maps/pr-86139-map.yaml
> +  text: <NONE>
A new release note was added for this PR, see:
https://github.com/kubernetes/kubernetes/pull/86139#issue-536041701

Please add the new note from there to here.

2022-11-14 17:31 UTC, ramrodo requested changes
Some improvements were suggested.

2022-11-16 00:04 UTC, AnaMMedina21 commented
Just added changes, and rebased. Thanks for the help, Rodolfo! 
/assign @ramrodo

2022-11-16 06:30 UTC, ramrodo commented
Great! @AnaMMedina21 
/lgtm
/approve

2022-11-16 06:30 UTC, merged