Update release notes draft to version v1.29.0-alpha.2
kubernetes/sig-release pull request #2361
Opened 2023-10-18 16:48 UTC by fykaa

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
This PR updates the Release Notes Draft to k/k v1.29.0-alpha.2

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

2023-10-26 20:25 UTC, rashansmith commented
@fsmunoz @fykaa did we finalize whether all text should be encapsulated in '' vs. none at all? Otherwise everything looks good!

2023-10-29 17:20 UTC, fsmunoz commented
> @fsmunoz @fykaa did we finalize whether all text should be encapsulated in '' vs. none at all? Otherwise everything looks good!

If there's the need for escaping things (and starting the line with backticks is one common reason, but there are more), both should work. If things are single-quoted, we shouldn't change them, if there's a need to quote it, both can work.

2023-10-29 17:32 UTC, fsmunoz requested changes
Great work @fykaa ; these are some minor suggested changes.

2023-10-29 17:32 UTC, fsmunoz commented on releases/release-1.29/release-notes/maps/pr-119732-map.yaml
> +    empty selector, i.e., "{}," is specified in a Pod Disruption Budget (PDB).
```suggestion
  text: 'Fixed an issue related to not draining all the pods in a namespace when an empty selector, i.e., "{}," is specified in a Pod Disruption Budget (PDB).'
```

2023-10-29 17:32 UTC, fsmunoz commented on releases/release-1.29/release-notes/maps/pr-119735-map.yaml
> +    directory already exists on the node.
```suggestion
  text: Volume attach or publish operation will not fail at `kubelet` if target path
    directory already exists on the node.
```

2023-10-29 17:32 UTC, fsmunoz commented on releases/release-1.29/release-notes/maps/pr-120338-map.yaml
> +    handle a mix of allocated and unallocated claims correctly.'
```suggestion
  text: '`k8s.io/dynamic-resource-allocation/controller:` `UnsuitableNodes` can now
    handle a mix of allocated and unallocated claims correctly.'
```

2023-10-29 17:32 UTC, fsmunoz commented on releases/release-1.29/release-notes/maps/pr-120400-map.yaml
> +    generation and validation of bootstrap tokens'
```suggestion
  text: '`cluster-bootstrap`: improved the security of the functions responsible for
    generation and validation of bootstrap tokens.'
```

2023-10-29 17:32 UTC, fsmunoz commented on releases/release-1.29/release-notes/maps/pr-120729-map.yaml
> +    APIs for specifying a context and logger.'
```suggestion
  text: '`client-go`: `k8s.io/client-go/tools` events and record packages now have new
    APIs for specifying a context and logger.'
```

2023-10-29 17:32 UTC, fsmunoz commented on releases/release-1.29/release-notes/maps/pr-120828-map.yaml
> +    is passed even if it is not required by the subcommand.'
```suggestion
  text: '`kubeadm`: Fixed the bug where it always did CRI detection when `--config`
    was passed, even if it is not required by the subcommand.'
```

2023-10-29 17:32 UTC, fsmunoz commented on releases/release-1.29/release-notes/maps/pr-120871-map.yaml
> +    as `potential` node.
```suggestion
  text: |-
    `k8s.io/dynamic-resource-allocation`: can now handle a `selected` node which isn't listed
    as `potential` node.
```

2023-10-29 17:32 UTC, fsmunoz commented on releases/release-1.29/release-notes/maps/pr-120877-map.yaml
> +    `generate-groups.sh` script.'
```suggestion
  text: 'Fixed a regression (`CLIENTSET_PKG: unbound variable`) when invoking deprecated
    `generate-groups.sh` script.'
```

2023-10-31 09:32 UTC, fykaa commented
Thanks a lot for the review @fsmunoz @rashansmith. Resolved

2023-10-31 09:33 UTC, fsmunoz commented
Great work @fykaa,  thanks @rashansmith for your review!

/lgtm 

Needs approval @kubernetes/release-team-leads

2023-10-31 09:40 UTC, Priyankasaggu11929 commented
/approve

Thanks everyone for the great work! :pray:

2023-10-31 09:46 UTC, merged

2023-10-31 18:37 UTC, kumarankit999 reviewed
Looks nice