V1.29 final release-notes draft
kubernetes/sig-release pull request #2391
Opened 2023-12-11 12:10 UTC by fsmunoz

What type of PR is this:
/kind cleanup
/kind documentation

What this PR does / why we need it:

This PR refactors and fine-tunes all the release-notes for v1.29.0, and adds manual sections:

* Major Themes: link to the upcoming release article
* Known issues: add the issues collected in the umbrella issue.

2023-12-11 12:40 UTC, fsmunoz commented
/retitle WIP: v1.29 final release-notes draft

2023-12-11 14:53 UTC, fsmunoz commented
/retitle v1.29 final release-notes draft

2023-12-11 14:56 UTC, fsmunoz commented
I've reflected the Known Issue (https://github.com/kubernetes/kubernetes/issues/121886), please take a look
/cc @pacoxu @SergeyKanzhelev

I've added the cloud provider removal to the Urgent Updates, as per our conversation. It is also present in the list, but I've added a paragraph in that sections with content from the mid-cycle blog.

/cc @sftim

2023-12-11 15:00 UTC, sftim commented on releases/release-1.29/release-notes/release-notes-draft.md
> +- In-tree cloud providers are now switched off by default. This change will require that users who are currently using in-tree cloud provider integrations (Azure, GCE, or vSphere) enable external clo
LGTM - and thank you.

2023-12-11 15:01 UTC, sftim commented on releases/release-1.29/release-notes/release-notes-draft.md
> +- In-tree cloud providers are now switched off by default. This change will require that users who are currently using in-tree cloud provider integrations (Azure, GCE, or vSphere) enable external clo
A nit. We can ship without this amendment (IMO).
```suggestion
- In-tree cloud provider integrations are now switched off by default. This change will require that users who are currently using in-tree cloud provider integrations (Azure, GCE, or vSphere) enable external cloud controller managers, or opt in to the legacy integration by setting the associated feature gates to  `false`. For more information about how to enable and run external cloud controller managers, read [Cloud Controller Manager Administration](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/) and [Migrate Replicated Control Plane To Use Cloud Controller Manager](https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration/). ([#117503](https://github.com/kubernetes/kubernetes/pull/117503), [@dims](https://github.com/dims))
```

2023-12-11 15:35 UTC, fykaa commented
lgtm!

2023-12-12 06:21 UTC, Priyankasaggu11929 commented
/lgtm
/approve

/hold
(Please unhold, when ready to merge)

Thank you everyone! :pray:

2023-12-12 06:37 UTC, sanchita-07 requested changes
lgtm!

2023-12-12 06:39 UTC, sanchita-07 requested changes
PLEG (Pod Lifecycle Event Generator) feature

2023-12-12 11:15 UTC, fsmunoz commented
> PLEG (Pod Lifecycle Event Generator) feature

I've added that to the description, while keeping it out of the title to keep is shorter.

2023-12-12 11:41 UTC, fsmunoz commented
Squashed in anticipation of merge (more reviews/fixes are still welcomed though).

2023-12-12 13:39 UTC, Priyankasaggu11929 commented
re-applying lgtm :slightly_smiling_face: 

/lgtm

2023-12-13 11:10 UTC, fsmunoz commented
Added the `SchedulerQueueingHints` issue to Known Issues; wording based on the conversation in the channel, with a link to the PR.

/cc @sanposhiho

2023-12-13 16:33 UTC, Priyankasaggu11929 commented
/lgtm
/approve

2023-12-13 17:05 UTC, fsmunoz commented
Squashed for merge, all reviews addressed.

@Priyankasaggu11929 take it a way!

2023-12-13 17:07 UTC, Priyankasaggu11929 commented
/lgtm

final lgtm :smile: :heart:

2023-12-13 17:08 UTC, Priyankasaggu11929 commented
/unhold

2023-12-13 17:08 UTC, kumarankit999 reviewed
lgtm!!!

2023-12-13 17:10 UTC, Priyankasaggu11929 commented
maybe a missed webhook :joy: 

trying again!

/lgtm

2023-12-13 17:14 UTC, merged