Update pr-124665-map.yaml
kubernetes/sig-release pull request #2540
Opened 2024-06-24 16:22 UTC by satyampsoni

Need to get this PR merged, to overcome the YAML Parsing conflict.
![image](https://github.com/kubernetes/sig-release/assets/94950988/5637270c-d219-4282-b37a-b6fbcc31fbee)

This is similar to https://kubernetes.slack.com/archives/CN1KH4K9A/p1712851737222339 and the respective PR that fixed the issue earlier https://github.com/kubernetes/sig-release/pull/2473/files.

cc @npolshakova

2024-06-24 16:24 UTC, npolshakova approved these changes

2024-06-24 17:24 UTC, sanchita-07 approved these changes
/approve

2024-06-24 17:26 UTC, sanchita-07 commented
cc @neoaggelos @Priyankasaggu11929 for approving the PR.

2024-06-24 17:35 UTC, Priyankasaggu11929 requested changes

2024-06-24 17:35 UTC, Priyankasaggu11929 commented on releases/release-1.31/release-notes/maps/pr-124665-map.yaml
> +  text: "`kubeadm`: Improved the 'IsPrivilegedUser' preflight check to not fail on certain Windows setups."
```suggestion
  text: "`kubeadm`: Improved the `IsPrivilegedUser` preflight check to not fail on certain Windows setups."
```

2024-06-25 03:04 UTC, satyampsoni commented
@Priyankasaggu11929 please review now!

2024-06-25 03:43 UTC, Priyankasaggu11929 commented
Thank you @satyampsoni :pray: 

/lgtm
/approve

2024-06-25 03:43 UTC, merged