Add krel release notes validation workflow
kubernetes/sig-release pull request #2698
Opened 2024-12-17 22:41 UTC by npolshakova

#### What type of PR is this:

/kind feature

#### What this PR does / why we need it:

Adds a GitHub Action to setup krel.

This is required to setup a presubmit job for PRs like: https://github.com/kubernetes/sig-release/pull/2659. The current requirement is to add validation using:

$ krel release-notes validate --help
krel release-notes validate <path-to-release-notes>

The 'validate' subcommand of krel has been developed to:

1. Check release notes maps for valid yaml.

2. Check release notes maps for valid punctuation.

```
Usage:
  krel release-notes validate [flags]

Flags:
  -h, --help                           help for validate
      --path-to-release-notes string   The path to the release notes to validate. Can be a top level directory or a specific file.
```

The release notes team is blocked whenever invalid yaml is merged into sig-release:

https://github.com/kubernetes/sig-release/pull/2589
https://github.com/kubernetes/sig-release/pull/2541

Invalid yaml can be introduced during the review process when people apply changes or manually edit the maps (not through krel, but in an editor). This workflow automates preventing invalid yaml from merging into sig-release.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/release/issues/2753

#### Special notes for your reviewer:
Based on @Vyom-Yadav's GitHub workflow: https://github.com/kubernetes-sigs/release-actions/pull/101

2024-12-18 12:38 UTC, Vyom-Yadav commented
/assign

2025-01-05 08:51 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> -          files: releases/**/*.yaml
@npolshakova I removed this section. `changed-files` are being calculated in the next step (using bash and git) and this wasn't being used anywhere.

2025-01-05 08:51 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> -            access_token: ${{ github.token }}
We're using:

```yaml
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
```

So, I don't think this is required.

2025-01-05 08:52 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +              echo "invalid_files=$(echo -n "$INVALID_FILES")" >> "$GITHUB_OUTPUT"
I don't see any reason to add it to `GITHUB_ENV`.

2025-01-05 08:54 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +          KREL_VERSION=v0.17.12
I've pinned this to `v0.17.12`, if and when we do a new release of `krel`, we'd need to update this. (I think there may be some automated job to do that, or we can add this to the handbook (for the lead to update it). 

Alternatively, do we want to fetch the latest release?

2025-01-08 15:00 UTC, npolshakova commented on .github/workflows/krel-release-notes-validate.yaml
> +          KREL_VERSION=v0.17.12
Hm, currently the handbook suggests the docs team uses the lastest krel, so maybe it's fine just fetching the latest release? https://github.com/kubernetes/sig-release/blob/ff03da9043cdd4cfd63f4c06c901909a744f2daa/release-team/role-handbooks/docs/README.md#tools

2025-01-08 15:01 UTC, npolshakova commented on .github/workflows/krel-release-notes-validate.yaml
> -          files: releases/**/*.yaml
Perfect!

2025-01-11 10:44 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +          KREL_VERSION=v0.17.12
Done, I changed to latest.

2025-01-11 10:45 UTC, Vyom-Yadav commented
Test run: https://github.com/npolshakova/sig-release/actions/runs/12723351941/job/35468384786?pr=4
Test comment: https://github.com/npolshakova/sig-release/pull/4#issuecomment-2585193169

2025-01-11 10:46 UTC, Vyom-Yadav commented
/remove hold

2025-01-11 10:52 UTC, Vyom-Yadav commented
/assign @npolshakova

2025-01-12 02:58 UTC, npolshakova commented
Changes look good @Vyom-Yadav! 
![Uploading image.png…]()

Is there a way to make this workflow required when merging release notes changes in? @kubernetes/sig-release-leads

2025-01-13 16:25 UTC, Vyom-Yadav commented
I think required workflows might not be supported anymore (for new workflows - https://docs.github.com/en/enterprise-server@3.11/actions/sharing-automations/required-workflows), but a github admin can check that for us. Anyways, that can only be enabled after merging this action.

2025-01-14 19:51 UTC, stmcginnis commented
/lgtm

2025-01-15 09:58 UTC, cpanato requested changes
some comments

thanks for doing this

2025-01-15 09:58 UTC, cpanato commented on .github/workflows/krel-release-notes-validate.yaml
> +
add

```
permissions: {}
```

this will drop all permissions for the workflow, as we dont need

2025-01-15 09:58 UTC, cpanato commented on .github/workflows/krel-release-notes-validate.yaml
> +    if: ${{ !github.event.pull_request.draft }}
add

```
permissions:
   contents: read
```

we might just need the contents read to be able to clone

2025-01-15 09:58 UTC, cpanato commented on .github/workflows/krel-release-notes-validate.yaml
> +      - id: install-krel
i think this is fine for now, we can add install krel action in the release-actions repo.

2025-01-15 09:58 UTC, cpanato commented on .github/workflows/krel-release-notes-validate.yaml
> +            }
nit: new line

2025-01-15 09:58 UTC, cpanato commented on .github/workflows/krel-release-notes-validate.yaml
> +      - name: Comment on PR if invalid yaml detected
i think this will not work as expected because in fork PRs we dont have the `write` permission for the github token

i would add this as job summary and then we can see this in the checks tab

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-job-summary

2025-01-15 18:02 UTC, puerco commented on .github/workflows/krel-release-notes-validate.yaml
> +      - name: Comment on PR if invalid yaml detected
I agree. It only needs `pull-requests` but I'd prefer to keep the token with less permissions. Just fail it and we can check the results on the workflow run.

2025-01-16 09:48 UTC, Vyom-Yadav commented
New test run: https://github.com/npolshakova/sig-release/actions/runs/12806142763?pr=4

2025-01-16 09:49 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +      - releases/**/release-notes/**.yml
Removed.

2025-01-16 09:51 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +          # we need to fetch the full history in order to check changes across all commits on the branch
We do `CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- releases/ | grep -E '\.ya?ml$' || true)`, so need fetch-depth 0. I removed the comment though (I think that is just extra)

2025-01-16 09:52 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +      - name: Comment on PR if invalid yaml detected
Migrated to github job summary. Test run: https://github.com/npolshakova/sig-release/actions/runs/12806142763?pr=4

2025-01-16 09:53 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +            }
Added a new line at the end.

2025-01-16 09:54 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +    if: ${{ !github.event.pull_request.draft }}
Since, it is a public repo, I don't think this is required. actions/checkout directly uses git, so I don't think we need to add any permission to the `github_token`

2025-01-16 09:54 UTC, Vyom-Yadav commented on .github/workflows/krel-release-notes-validate.yaml
> +
Added.

2025-01-23 20:44 UTC, puerco commented on .github/workflows/krel-release-notes-validate.yaml
> +          # we need to fetch the full history in order to check changes across all commits on the branch
Yeah I only meant the comment :)

2025-01-23 20:44 UTC, puerco commented
OK, let's kick the tires on this! :rocket: 
/lgtm
/approve

2025-01-23 20:45 UTC, merged