Create 1.33 release directory
kubernetes/sig-release pull request #2706
Opened 2024-12-23 17:18 UTC by npolshakova

#### What type of PR is this:
/kind documentation

#### What this PR does / why we need it:
Creates the 1.33 release directory as per https://github.com/kubernetes/sig-release/issues/2705 

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:

2024-12-23 19:50 UTC, gracenng commented on releases/release-1.33/README.md
> +* [Bug Triage Tracking Board](https://bit.ly/k8s133-bugtriage)
Don't think we have the CI Signal board anymore, but not sure about Bug Triage

2025-01-08 21:00 UTC, npolshakova commented on releases/release-1.33/README.md
> +* [Bug Triage Tracking Board](https://bit.ly/k8s133-bugtriage)
@Vyom-Yadav can you confirm we don't have a CI Signal board anymore? I can remove this link!

2025-01-08 21:02 UTC, johnbelamaric commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
This looks *at least* 1 week too early. It gives us only 3 weeks for code/test. We need at least 4 weeks, which is what we had in 1.32 and that was actually the shortest code+test we had in the last 12 releases...

See https://docs.google.com/spreadsheets/d/1r7nv5qeSPbU2OieEht6U1it5m4QeS3Iv7a83ujbs7kU/edit?resourcekey=0-vc4oKe2uijpmpoeyjgRfEQ&gid=0#gid=0

@liggitt @thockin @deads2k @soltysh @wojtek-t

2025-01-08 21:19 UTC, johnbelamaric commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
IMO it should be 3/20.

2025-01-08 22:45 UTC, chanieljdan commented on releases/release-1.33/README.md
> +| Docs deadline — PRs ready for review                                                   | Docs Lead                     | Tuesday 18th March 2025
Last release cycle we had the PR ready for review deadline on week 11 to avoid kubecon NA, but for [1.30](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.30/README.md) and [1.31](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.31/README.md), the PR ready for review deadline was on week 10. I think giving 2 weeks between the Ready for Review deadline and Docs Freeze works better if we can.

2025-01-09 06:55 UTC, pacoxu commented on releases/release-1.33/release-team.md
> +| Release Team Lead | Nina Polshakova ([@npolshakova](https://github.com/npolshakova) / Slack: `@Nina Polshakova`) |                                        |
lead shadows can be added?

2025-01-09 21:57 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Docs deadline — PRs ready for review                                                   | Docs Lead                     | Tuesday 18th March 2025
@katcosgrove do you have any thoughts here? It's a little tricky because week 13 is KubeconEU.

2025-01-09 22:03 UTC, npolshakova commented on releases/release-1.33/release-team.md
> +| Release Team Lead | Nina Polshakova ([@npolshakova](https://github.com/npolshakova) / Slack: `@Nina Polshakova`) |                                        |
Added in https://github.com/kubernetes/sig-release/pull/2706/commits/644819125816bcfeb1b3955c22ec984910756dd4! Substeam leads will add their shadows separately once the selection is complete.

2025-01-10 04:32 UTC, Vyom-Yadav commented on releases/release-1.33/README.md
> +* [Bug Triage Tracking Board](https://bit.ly/k8s133-bugtriage)
Yeah, we still have both. The schema is really different, but maybe we can unify them with views. This would also require modifying the bug triage automation scripts we have, so quite an action item. I'll look into it more.

2025-01-10 04:46 UTC, Vyom-Yadav requested changes
Some comments on board observation and column naming:

2025-01-10 04:46 UTC, Vyom-Yadav commented on releases/release-1.33/README.md
> +| Start of Release Cycle                                                                 | Lead                          | Monday 13th January 2025
I don't think this should be just `master-blocking`. It should include both `master-blocking, master-informing`

2025-01-10 04:46 UTC, Vyom-Yadav commented on releases/release-1.33/README.md
> +| 1.33.0-alpha.2 released                                                                | Branch Manager                | Tuesday 18th February 2025
Both boards are observed from the start of the release, so given the previous comment is accepted, I think we can remove this.

2025-01-10 04:46 UTC, Vyom-Yadav commented on releases/release-1.33/README.md
> +| **Docs Freeze**                                                                        | Docs Lead                     | Tuesday 25th March 2025
`1.33-informing` should also be included.

2025-01-10 04:46 UTC, Vyom-Yadav commented on releases/release-1.33/README.md
> +| Release blog published                                                                 | Comms                         | Wednesday 16th April 2025
Isn't the pattern for this column, update only when boards change? If so, I think this can be removed.

2025-01-10 04:46 UTC, Vyom-Yadav commented on releases/release-1.33/README.md
> +|----------------------------------------------------------------------------------------|-------------------------------|-----------------------------------------------------------------------------
Should this column still be called `CI Signal`? 

Yes - CI Signal and Bug Triage are components of Release Signal. 
No - There is no CI Signal team, it should be called Release Signal.

2025-01-10 15:03 UTC, danielchan-cyera commented on releases/release-1.33/README.md
> +| Docs deadline — PRs ready for review                                                   | Docs Lead                     | Tuesday 18th March 2025
I'm thinking we move the PR ready for review deadline ahead to week 10

2025-01-10 15:04 UTC, chanieljdan commented on releases/release-1.33/README.md
> +| Docs deadline — PRs ready for review                                                   | Docs Lead                     | Tuesday 18th March 2025
I'm thinking we move the PR Ready fro Review Deadline ahead to week 10

2025-01-10 16:20 UTC, soltysh commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
> Can we make it policy to have no less than 4 for dev?

Definitely agree wrt making a strict policy for 4 dev weeks after the enhancement freeze.

2025-01-10 17:20 UTC, johnbelamaric commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
*at least* 4 weeks...

2025-01-10 17:22 UTC, johnbelamaric commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
> But really, it began the moment the tree unfroze. So we have (had) a lot more than just 3 weeks for dev. But the holidays ate all of December, so in PRACTICE, not really.

Yes, for things that we had agreed on the design for in the *previous cycle* and for bug fixes. But for anything we want to design & deliver this cycle, we need time in this cycle for dev+test.

2025-01-13 00:37 UTC, npolshakova commented on releases/release-1.33/README.md
> +* [Bug Triage Tracking Board](https://bit.ly/k8s133-bugtriage)
Sounds good, so no changes here in the README?

2025-01-13 00:42 UTC, npolshakova commented on releases/release-1.33/README.md
> +| **Docs Freeze**                                                                        | Docs Lead                     | Tuesday 25th March 2025
Should is also be included for `**v1.33.0 released**`?

2025-01-13 00:42 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Release blog published                                                                 | Comms                         | Wednesday 16th April 2025
Which pattern? Can you highlight the diff?

2025-01-13 00:43 UTC, npolshakova commented on releases/release-1.33/README.md
> +|----------------------------------------------------------------------------------------|-------------------------------|-----------------------------------------------------------------------------
This is from the previous releases, but I agree- let's change it to `Release Signal`.

2025-01-13 00:53 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Call for [Exceptions][Exception]                                                       | Lead                          | Monday 24th February 2025
I agree- I think calling for exceptions should happen as soon as the enhancements freeze is complete and then a follow-up reminder closer to the code freeze. Do we need two reminders here in the list? I'm thinking the first reminder can be sent as part of the enchancement freeze outreach?

2025-01-13 00:59 UTC, npolshakova commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
What was the consensus here- do we want to extend the cycle and add an extra week for dev+test after the enhancement freeze? @liggitt @thockin @deads2k @soltysh @wojtek-t 

For context the last spring release (1.30) had a similar timeline: https://github.com/kubernetes/sig-release/tree/master/releases/release-1.30. Week 5 was the start of the enhancement freeze, week 9 was code freeze.

2025-01-13 02:27 UTC, johnbelamaric commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
In 1.30 though there was a separate code and test freeze - and test freeze was week 12. We have decided splitting code and test freeze encourages merging without tests, which is not healthy.

I think 3/20 should be code+test but would be good to hear others' opinions.

2025-01-13 10:43 UTC, soltysh commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
First of all the math here doesn't add up wrt weeks (comparing current dates with [last release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.32#timeline):
W1: 1/13 (Monday first day of week 1)
W2: 1/20
W3: 1/27
W3: 2/03
W4: 2/10
W5: 2/17
W6: 2/24
W7: 3/03
W8: 3/10
W9: 3/17
So at minimum I'd expect 3/17 to be the code freeze. But I'm willing to support John's proposal of 3/20, but that means W10, not 11 based on what I wrote above.

2025-01-13 12:21 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +|----------------------------------------------------------------------------------------|-------------------------------|-----------------------------------------------------------------------------
Agreed, this collumn is mainly about list of test boards need to be monitored during release circle, we should call it as Release Signal. This is a really good point, this table should be updated.

2025-01-13 12:21 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +| Start of Release Cycle                                                                 | Lead                          | Monday 13th January 2025
+1

2025-01-13 12:21 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +| 1.33.0-alpha.2 released                                                                | Branch Manager                | Tuesday 18th February 2025
+1

2025-01-13 12:21 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +| Release blog published                                                                 | Comms                         | Wednesday 16th April 2025
what Vyom means is the Release Signal/CI Signal colum here is only update list of dashboards we should monitor. 
- From week 1 to 12: monitor `master-blocking`,  `master-informing`
- From week 12 to the end: monitor `master-blocking`,  `master-informing`, 1.33-blocking`, `1.33-informing`

=> so you need to edit 2 rows only and remove the rest.
- First row Start of Release Cycle - week 1: put `master-blocking`,  `master-informing`.
- 1.33.0-rc.0 released - week 12: put `master-blocking`,  `master-informing`, 1.33-blocking`, `1.33-informing`.
------------
- Begin [Enhancements Freeze] - week 5: remove [master-blocking], [master-informing] => we don't need them in the middle here, as mentioned above,  [master-blocking], [master-informing]  are also presented from week 1 to 12.
- v1.33.0 released - week 5: remove [1.33-blocking], [master-blocking], [master-informing] => similarly, as mentioned above, from week 12 to the end, we monitor 4 dashboards.

2025-01-13 12:32 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +| **Docs Freeze**                                                                        | Docs Lead                     | Tuesday 25th March 2025
@npolshakova nope, we don't need to put [1.33-blocking], [1.33-informing], [master-blocking], [master-informing] at the end for **v1.33.0 released**. We should put these 4 dashboards at the row of **1.33.0-rc.0 released**, week 12 only. My next comment below will help you understand it.

P/S: These issue should be noticed in previous release, glad that we point them out now.

2025-01-13 15:16 UTC, npolshakova commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
I agree- I think Week 10 code freeze will give people more time. @katcosgrove would this work with the docs deadlines?

2025-01-13 15:17 UTC, npolshakova commented on releases/release-1.33/README.md
> +| **Docs Freeze**                                                                        | Docs Lead                     | Tuesday 25th March 2025
Okay sounds good- I'll remove the dashboard on the `v1.33.0 released.` row and only keep the week 12 dashboards. Thanks for clarifying!

2025-01-13 15:18 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Release blog published                                                                 | Comms                         | Wednesday 16th April 2025
Thanks for the write up! That makes sense- I'll update the chart to reflect that then!

2025-01-13 15:21 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Release blog published                                                                 | Comms                         | Wednesday 16th April 2025
Addressed in https://github.com/kubernetes/sig-release/pull/2706/commits/5462dd449d96d07706694e1b53f7b3325935044c

2025-01-13 15:21 UTC, npolshakova commented on releases/release-1.33/README.md
> +| **Docs Freeze**                                                                        | Docs Lead                     | Tuesday 25th March 2025
Addressed in https://github.com/kubernetes/sig-release/pull/2706/commits/5462dd449d96d07706694e1b53f7b3325935044c

2025-01-13 15:22 UTC, npolshakova commented on releases/release-1.33/README.md
> +| 1.33.0-alpha.2 released                                                                | Branch Manager                | Tuesday 18th February 2025
Addressed in https://github.com/kubernetes/sig-release/pull/2706/commits/70f1e66a73e736ef25bb7110ab2b72e83863f6e4

2025-01-13 15:22 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Start of Release Cycle                                                                 | Lead                          | Monday 13th January 2025
Updated!

2025-01-13 15:23 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Docs deadline — PRs ready for review                                                   | Docs Lead                     | Tuesday 18th March 2025
Moved “Docs deadline — PRs ready for review” ahead to week 10 in https://github.com/kubernetes/sig-release/pull/2706/commits/70f1e66a73e736ef25bb7110ab2b72e83863f6e4

2025-01-13 16:32 UTC, Vyom-Yadav commented on releases/release-1.33/README.md
> +| Call for [Exceptions][Exception]                                                       | Lead                          | Monday 24th February 2025
I think "what exactly was supposed to happen" is a comment on the item, "<Hey, you missed the freeze> please file an exception request if required". 

This _also_ includes writing to the mailing list about XYZ freeze in place and that exception requests can be filed.

2025-01-14 13:39 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +* [Bug Triage Tracking Board](https://bit.ly/k8s133-bugtriage)
@npolshakova could please help me update the link for 1.33 Bug Triage board: https://github.com/orgs/kubernetes/projects/80/views/24? Many thanks for this.

2025-01-14 13:39 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +* [CI Signal Project Board & Issue Tracking](https://bit.ly/k8s133-cisignal)
And update the link for 1.33 CI Signal Board as well: https://github.com/orgs/kubernetes/projects/68/views/37

2025-01-14 14:20 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +* [Bug Triage Tracking Board](https://bit.ly/k8s133-bugtriage)
solved

2025-01-14 14:21 UTC, wendy-ha18 commented on releases/release-1.33/README.md
> +* [CI Signal Project Board & Issue Tracking](https://bit.ly/k8s133-cisignal)
solved

2025-01-15 16:45 UTC, katcosgrove commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
I am fine with pushing code freeze to week 10. Week 11 is too close to Docs Freeze, considering SIGs already struggle to meet documentation deadlines. I am unwilling to increase pressure on Release Docs and SIG Docs by shortening that timeline even further.

2025-01-15 19:34 UTC, johnbelamaric commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
Ok, so that is the Thursday of Week 10, which starts on 3/24 based on @soltysh's calculations? In other words, 3/27?

Or did you mean 3/20 @katcosgrove ? It seems the math was wrong at some point?

2025-01-15 19:38 UTC, johnbelamaric commented on releases/release-1.33/README.md
> +| Begin Friday APAC-friendly meetings                                                    | Lead                          | Wednesday 2nd January 2025
the dates are all messed up here, this is causing confusion. Can we fix the dates? See https://github.com/kubernetes/sig-release/pull/2706#discussion_r1912990535

2025-01-16 20:37 UTC, npolshakova commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
I meant week 10, 3/20. I think the dates and week mappings are fixed here now: https://github.com/kubernetes/sig-release/blob/86947d89fc9958baecf88c66c2336fb3f51b4ab7/releases/release-1.33/README.md

2025-01-16 20:37 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Begin Friday APAC-friendly meetings                                                    | Lead                          | Wednesday 2nd January 2025
Ty! Fixed here: https://github.com/kubernetes/sig-release/blob/86947d89fc9958baecf88c66c2336fb3f51b4ab7/releases/release-1.33/README.md

2025-01-16 20:39 UTC, npolshakova commented on releases/release-1.33/README.md
> +| Release Highlights deadline                                                            | Comms                         | Tuesday 25th March 2025
@mbianchidev @rytswd Updated the `Release Highlights deadline` to be before `Release blog ready to review` based on https://kubernetes.slack.com/archives/C2C40FMNF/p1736496690555129?thread_ts=1735581655.943799&cid=C2C40FMNF. Let me know how this looks like from the Comms perspective.

2025-01-17 13:17 UTC, npolshakova commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
Also updated docs freeze back to week 13: https://github.com/kubernetes/sig-release/pull/2706/commits/c6fb0f32e751122604a7a499927d002964cdd670 @katcosgrove @chanieljdan @rayandas  let me know what you think of the deadlines for the last couple weeks!

2025-01-17 18:16 UTC, thockin commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
thanks!

2025-01-17 18:20 UTC, johnbelamaric commented on releases/release-1.33/README.md
> +| **Begin [Code Freeze] and [Test Freeze]**                                              | Branch Manager                | 02:00 UTC Friday 7th March 2025 / 19:00 PDT Thursday 6th March 2025
great, thanks! lgtm

2025-01-17 19:57 UTC, gracenng approved these changes
/lgtm

could you please a [timezone link](https://everytimezone.com) for our major deadline in a following PR

2025-01-17 20:31 UTC, katcosgrove commented
@Vyom-Yadav could you please remove your change request?

2025-01-17 20:41 UTC, Vyom-Yadav commented
> @Vyom-Yadav could you please remove your change request?

Does that prevent a PR from merging? I thought prow did it irrespective of whether a 'requested changes' is pending.

2025-01-17 20:58 UTC, npolshakova commented
I think this needs an approval from someone in @kubernetes/sig-release-leads to merge

2025-01-17 20:59 UTC, katcosgrove commented
/approve

2025-01-17 20:59 UTC, katcosgrove commented
Dang, though I had the perms for this.

/assign @jeremyrickard

2025-01-18 16:04 UTC, merged